### ISSUE TITLE
 export.py : cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated'

### ISSUE THREAD

**Issue by xinsuinizhuan** [hukaixuan19970627/yolov5_obb#142]

**Comment by xinsuinizhuan** [comment]
(yolov5) E:\Item\Item_done\yolo\yolo5\yolov5_obb>python export.py --weights best.pt
Traceback (most recent call last):
  File "export.py", line 57, in <module>
    from models.common import Conv
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\models\common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\__init__.py)

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/148719213-460704ea-bb52-47d2-9425-e68a1f6417d4.png)
Check your requirements first， you should refer to [install.md](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md)

**Comment by xinsuinizhuan** [comment]
根据install.md安装环境，python setup.py develop失败：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:35_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28845127_0

我的torch版本：
torch                   1.7.1+cu110
torchaudio              0.7.2
torchvision             0.8.2+cu110

切换到utils\nms_rotated下执行：python setup.py develop失败
我的笔记本3060ti显卡，只支持 compute_52,sm_52
nvcc fatal   : Unsupported gpu architecture 'compute_86'
哪里改这个_86?
失败日志：
(yolov5_obb) E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated>python setup.py develop
running develop
C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing manifest file 'nms_rotated_ext.egg-info\SOURCES.txt'
running build_ext
C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Emitting ninja build file E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\build\temp.win-amd64-3.9\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\ProgramData\Anaconda3\envs\yolov5_obb\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\src\poly_nms_cuda.cu -o E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\build\temp.win-amd64-3.9\Release\src/poly_nms_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86
FAILED: E:/Item/Item_done/yolo/yolo5/yolov5_obb/utils/nms_rotated/build/temp.win-amd64-3.9/Release/src/poly_nms_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\ProgramData\Anaconda3\envs\yolov5_obb\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\src\poly_nms_cuda.cu -o E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\build\temp.win-amd64-3.9\Release\src/poly_nms_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\ProgramData\Anaconda3\envs\yolov5_obb\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\src\nms_rotated_cuda.cu -o E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\build\temp.win-amd64-3.9\Release\src/nms_rotated_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86
FAILED: E:/Item/Item_done/yolo/yolo5/yolov5_obb/utils/nms_rotated/build/temp.win-amd64-3.9/Release/src/nms_rotated_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\ProgramData\Anaconda3\envs\yolov5_obb\include -IC:\ProgramData\Anaconda3\envs\yolov5_obb\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" -c E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\src\nms_rotated_cuda.cu -o E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\build\temp.win-amd64-3.9\Release\src/nms_rotated_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Item\Item_done\yolo\yolo5\yolov5_obb\utils\nms_rotated\setup.py", line 178, in <module>
    setup(
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "C:\ProgramData\Anaconda3\envs\yolov5_obb\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by hukaixuan19970627** [comment]
遇到问题可以先尝试用搜索引擎解决。这属于环境安装方面的问题，应该是硬件算力和torch算力不匹配的原因，换个torch版本就行。一般都是安装当前cuda驱动能够支持的最高版本torch

**Comment by hukaixuan19970627** [comment]
对了，显卡尽量安装可支持的最高版本的CUDA驱动，高版本驱动可以向下兼容低版本的软件平台，反过来可不行

**Comment by xinsuinizhuan** [comment]
好的。我还以为，我当前是cuda11.0，必须安装相应的torch cuda11.0的版本。可以安装高版本的cuda1.0.1?

**Comment by xinsuinizhuan** [comment]
> 对了，显卡尽量安装可支持的最高版本的CUDA驱动，高版本驱动可以向下兼容低版本的软件平台，反过来可不行

嗯嗯。主要我这边目前还配置了paddle,paddle比较鸡肋，目前给的库，指支持到了cuda11.0，所以没法配置高版本cuda驱动。

**Comment by hukaixuan19970627** [comment]
我的install.md里有验证版本过程，一步步照着检查就行, 总共有三个版本需要你注意：
CUDA Driver Version， CUDA Toolkit Version（runtime version），torch的cuda version
查看命令分别为nvidia-smi, nvcc -V, torch.version.cuda。
版本大小关系为 CUDA Driver Version ≥ CUDA Toolkit Version（runtime version）= torch.version.cuda

**Comment by hukaixuan19970627** [comment]
> > 对了，显卡尽量安装可支持的最高版本的CUDA驱动，高版本驱动可以向下兼容低版本的软件平台，反过来可不行
> 
> 嗯嗯。主要我这边目前还配置了paddle,paddle比较鸡肋，目前给的库，指支持到了cuda11.0，所以没法配置高版本cuda驱动。

... 所以建议你安装高版本驱动撒，CUDA Toolkit Version 可以安装多个版本，可随时通过该路径来切换版本，第三方库指代的cuda都是CUDA Toolkit Version ，驱动是硬件平台版本，cuda是软件，驱动可以向下兼容低版本的软件的

**Comment by xxxjjjx** [comment]
请问你解决这个问题了吗？是怎么解决这个问题？安装高版本的torch？

**Comment by xinsuinizhuan** [comment]
嗯。我换了台电脑，安装了cuda11.3和对应的torch，基本就可以了。

**Comment by xxxjjjx** [comment]
我的环境cuda11.0 torch=1.7.1。然后就报错。是cuda太低？

**Comment by hukaixuan19970627** [comment]
> 我的环境cuda11.0 torch=1.7.1。然后就报错。是cuda太低？

直接pip装编译好cuda的torch版本，一般编译cuda代码之类的问题会少一点。
不过高深度学习还是早入换linux系统比较好，很多包windows根本不支持的
