### ISSUE TITLE
Export TensorRT  ONNX?

### ISSUE THREAD

**Issue by Jim0530** [hukaixuan19970627/yolov5_obb#158]
想問一下這版本的Code 有支援輸出 ONNX 或 TensorRT嗎？

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/138

**Comment by Jim0530** [comment]
想請問一下 如果將解析度調整成 640*640
會出現以下Error 

Traceback (most recent call last):
  File "train.py", line 632, in <module>
    main(opt)
  File "train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 372, in train
    compute_loss=compute_loss)
  File "/home/lhlee/anaconda3/envs/sccheng-image/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/lhlee/Desktop/sccheng/yolov5_obb/val.py", line 206, in run
    out = non_max_suppression_obb(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls) # list*(n, [xylsθ, conf, cls]) θ ∈ [-pi/2, pi/2)
  File "/home/lhlee/Desktop/sccheng/yolov5_obb/utils/general.py", line 853, in non_max_suppression_obb
    _, i = obb_nms(rboxes, scores, iou_thres)
  File "/home/lhlee/Desktop/sccheng/yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py", line 40, in obb_nms
    inds = nms_rotated_ext.nms_rotated(dets_th, scores, iou_thr)
RuntimeError: CUDA error: device-side assert triggered

我記得您在您的文章中有提到新的版本會避免這個Error 
但我第二個Epoch的時候就會跳出來我該改程式中的哪個地方 謝謝？

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/147
