### ISSUE TITLE
训练报错: Not compiled with GPU support

### ISSUE THREAD

**Issue by dagongren11** [hukaixuan19970627/yolov5_obb#161]
大佬，训练的时候出现这个问题改怎么解决呀
![微信图片_20220113030925](https://user-images.githubusercontent.com/86774750/149206179-d176e2d8-13cc-44bc-a4a6-d506834b14e7.png)。

**Comment by hukaixuan19970627** [comment]
编译nms_rotated_ext时出了问题，把so文件删了重新编译一次。
另外应该先花十分钟按照getstart.md把所有demo先运行一遍确保环境没有问题之后，再开始自己的训练，不然出问题了就是浪费时间

**Comment by plt2mek** [comment]
i am facing the same issue : RuntimeError: Not compiled with GPU support
/////////////////////////////////////////////////////////
C:\Users\hocine\AppData\Local\Programs\Python\Python36\Python36\python.exe C:/Users/hocine/PycharmProjects/pythonProject_36/YOLTV5/detect.py
detect: weights=weights\best.pt, source=C:\IA, imgsz=[2048, 2048], conf_thres=0.3, iou_thres=0.4, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5  2022-4-2 torch 1.10.2+cu111 CUDA:0 (Quadro P2000, 5120MiB)

Fusing layers... 
Model Summary: 290 layers, 21640929 parameters, 0 gradients, 50.5 GFLOPs
Traceback (most recent call last):
  File "C:/Users/hocine/PycharmProjects/pythonProject_36/YOLTV5/detect.py", line 251, in <module>
    main(opt)
  File "C:/Users/hocine/PycharmProjects/pythonProject_36/YOLTV5/detect.py", line 246, in main
    run(**vars(opt))
  File "C:\Users\hocine\AppData\Local\Programs\Python\Python36\Python36\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:/Users/hocine/PycharmProjects/pythonProject_36/YOLTV5/detect.py", line 121, in run
    pred = non_max_suppression_obb(pred, conf_thres, iou_thres, classes, agnostic_nms, multi_label=True, max_det=max_det)
  File "C:\Users\hocine\PycharmProjects\pythonProject_36\YOLTV5\utils\general.py", line 853, in non_max_suppression_obb
    _, i = obb_nms(rboxes, scores, iou_thres)
  File "C:\Users\hocine\PycharmProjects\pythonProject_36\YOLTV5\utils\nms_rotated\nms_rotated_wrapper.py", line 41, in obb_nms
    inds = nms_rotated_ext.nms_rotated(dets_th, scores, iou_thr)
RuntimeError: Not compiled with GPU support

**Comment by zhanguser0614** [comment]
![image](https://user-images.githubusercontent.com/94903297/165037382-e520046b-4108-4892-ae4a-9c7dc91f7914.png)
大佬我出现了同样的问题，这个删除so文件是指nms_rotated_ext.cpython-39-x86_64-linux-gnu.so文件吗，我删了还是不好使，这是在跑源代码的demo时候出现的问题
