### ISSUE TITLE
issue: ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (/home/wenqing/yolov5_obb-master/utils/nms_rotated/__init__.py)

### ISSUE THREAD

**Issue by wq1108** [hukaixuan19970627/yolov5_obb#272]
(dota_yolov5) wenqing@amax:~/yolov5_obb-master$ python train.py
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    import val  # for end-of-epoch mAP
  File "/home/wenqing/yolov5_obb-master/val.py", line 28, in <module>
    from models.common import DetectMultiBackend
  File "/home/wenqing/yolov5_obb-master/models/common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/home/wenqing/yolov5_obb-master/utils/datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/home/wenqing/yolov5_obb-master/utils/augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "/home/wenqing/yolov5_obb-master/utils/general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "/home/wenqing/yolov5_obb-master/utils/nms_rotated/__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "/home/wenqing/yolov5_obb-master/utils/nms_rotated/nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (/home/wenqing/yolov5_obb-master/utils/nms_rotated/__init__.py)
想问下作者这个问题怎么解决啊 (直接跑的代码 没有修改除了路径 )试了一些方法 没有用

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/162434829-99a57a62-a9bb-4c5a-b16e-5a726cb4f905.png)
