### ISSUE TITLE
detect with pb model

### ISSUE THREAD

**Issue by Baiyixuan1113** [hukaixuan19970627/yolov5_obb#282]
您好，我在尝试测试使用您的代码由pt模型转换到tensorflow的pb模型并测试
我的环境：
- Ubuntu 18.04
- cuda 10.2
- torch 1.10.1
- tensorflow 2.8.0
应用您的代码我已经跑通了训练环节并得到了best.pt，并且应用您的export.py成功将pt模型转换成了pb模型，转换时执行的命令:
```
python export.py --weights=runs/train/exp/weights/best.pt --include pb
```
我可以应用您的detect.py正常在cpu上使用导出的pb模型测试，但是在gpu上却会报错，以下是预测是执行的命令和报错信息：
```
python detect.py --weights='/home/Data/Projects/yolov5_obb/runs/train/exp/weights/best.pb' --device=0
```
```
detect: weights=['/home/Data/Projects/yolov5_obb/runs/train/exp/weights/best.pb'], source=/home/Data/Projects/yolov5_obb/dataset/dataset_seal/val_data/images/, imgsz=[640, 640], conf_thres=0.3, iou_thres=0.4, max_det=1000, device=0, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 2022-4-8 torch 1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2080, 7981MiB)

Loading /home/Data/Projects/yolov5_obb/runs/train/exp/weights/best.pb for TensorFlow *.pb inference...
2022-04-13 18:49:08.662506: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.667993: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.668546: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.669236: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-13 18:49:08.669715: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.670284: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.670709: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.995717: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.996204: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.996650: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-13 18:49:08.997051: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6292 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080, pci bus id: 0000:01:00.0, compute capability: 7.5
2022-04-13 18:49:11.147784: I tensorflow/stream_executor/cuda/cuda_driver.cc:739] failed to allocate 6.14G (6598361088 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2022-04-13 18:49:11.768641: E tensorflow/stream_executor/cuda/cuda_dnn.cc:361] Loaded runtime CuDNN library: 8.0.3 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2022-04-13 18:49:11.769437: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : UNIMPLEMENTED: DNN library is not found.
Traceback (most recent call last):
  File "detect.py", line 252, in <module>
    main(opt)
  File "detect.py", line 247, in main
    run(**vars(opt))
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 116, in run
    pred = model(im, augment=augment, visualize=visualize)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Data/Projects/yolov5_obb/models/common.py", line 409, in forward
    y = self.frozen_func(x=self.tf.constant(im)).numpy()
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1601, in __call__
    return self._call_impl(args, kwargs)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py", line 244, in _call_impl
    args, kwargs, cancellation_manager)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1619, in _call_impl
    return self._call_with_flat_signature(args, kwargs, cancellation_manager)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1668, in _call_with_flat_signature
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1854, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 504, in call
    ctx=ctx)
  File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 55, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'model/tf_conv/sequential/conv2d/Conv2D' defined at (most recent call last):
    File "detect.py", line 252, in <module>
      main(opt)
    File "detect.py", line 247, in main
      run(**vars(opt))
    File "/home/etop/miniconda3/envs/py37_torch1.10.1_cu102/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
      return func(*args, **kwargs)
    File "detect.py", line 81, in run
      model = DetectMultiBackend(weights, device=device, dnn=dnn)
    File "/home/Data/Projects/yolov5_obb/models/common.py", line 358, in __init__
      frozen_func = wrap_frozen_graph(gd=graph_def, inputs="x:0", outputs="Identity:0")
    File "/home/Data/Projects/yolov5_obb/models/common.py", line 354, in wrap_frozen_graph
      tf.nest.map_structure(x.graph.as_graph_element, outputs))
Node: 'model/tf_conv/sequential/conv2d/Conv2D'
DNN library is not found.
         [[{{node model/tf_conv/sequential/conv2d/Conv2D}}]] [Op:__inference_pruned_2051]
```

请问是您的代码本身不支持pb模型的gpu环境预测吗？或是我的操作不当呢。希望得到您的回复。

**Comment by hukaixuan19970627** [comment]
https://github.com/tensorflow/tensorflow/issues/55309
