### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by TDStudou** [hukaixuan19970627/yolov5_obb#347]
大佬你好我已经对数据集文件进行了修改，但是在运行train.py的时候还是出现了问题
# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: C:\Users\TDS\media\test\DOTA\DOTAv1.5   # dataset root dir
train: train_split_1024_gap200/images    # train images (relative to 'path') 
val: val_split_1024_gap200/images   # val images (relative to 'path') 
test: test_split_1024/images  # test images (optional)

# Classes
nc: 2  # number of classes
names: ['ship','other']  # class names

# Download script/URL (optional)
# download: https://ultralytics.com/assets/coco128.zip
出现的错误代码为：
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\IndexKernel.cu:93: block: [0,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/3281 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\TDS\yolov5_obb\train.py", line 632, in <module>
    main(opt)
  File "C:\Users\TDS\yolov5_obb\train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "C:\Users\TDS\yolov5_obb\train.py", line 363, in train
    results, maps, _ = val.run(data_dict,
  File "C:\Users\TDS\Anaconda3\envs\Py39_Torch1.10_cu11.3\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TDS\yolov5_obb\val.py", line 199, in run
    loss += compute_loss([x.float() for x in train_out], targets)[1]  # box, obj, cls, theta
  File "C:\Users\TDS\yolov5_obb\utils\loss.py", line 178, in __call__
    obji = self.BCEobj(pi[..., 4], tobj)
  File "C:\Users\TDS\Anaconda3\envs\Py39_Torch1.10_cu11.3\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\TDS\Anaconda3\envs\Py39_Torch1.10_cu11.3\lib\site-packages\torch\nn\modules\loss.py", line 704, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "C:\Users\TDS\Anaconda3\envs\Py39_Torch1.10_cu11.3\lib\site-packages\torch\nn\functional.py", line 2982, in binary_cross_entropy_with_logits
    return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
您可否解答一下？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/170640481-25e0db1e-a70d-40c1-a024-1dba9bbb1531.png)
