### ISSUE TITLE
bug when trying to save txt bboxes with  detect.py --save-txt

### ISSUE THREAD

**Issue by vshesh** [hukaixuan19970627/yolov5_obb#375]
In Colab

```
%cd /content/yolov5_obb
!python detect.py --weights '/content/best.pt' --source '../datasets/sample/valid/images' --conf-thres 0.5 --img 640 --device 0 --agnostic-nms --save-txt
```

Result

```
/content/yolov5_obb
detect: weights=['/content/sample_data/best.pt'], source=../datasets/sample/valid/images, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.4, max_det=1000, device=0, view_img=False, save_txt=True, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=True, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 c7409ff torch 1.10.1+cu113 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

Fusing layers... 
Model Summary: 290 layers, 21584355 parameters, 0 gradients
Traceback (most recent call last):
  File "detect.py", line 251, in <module>
    main(opt)
  File "detect.py", line 246, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "detect.py", line 159, in run
    poly = poly.tolist()
AttributeError: 'list' object has no attribute 'tolist'
```

Removing `--save-txt` makes the error go away and detection is fine.

**Comment by vshesh** [comment]
I see sorry I'm supposed to use `val.py`.

**Comment by vshesh** [comment]
Actually now I am confused because you have detect.py at the bottom there that you are running with `--hide-txt --hide-conf`. This is useful for me because I have a `--source /some/folder` instead of a dataset with validation that needs to happen.

**Comment by archg2021** [comment]
@vshesh I ace the same error. Were you able to save the detected bounding boxes in text files?

**Comment by vshesh** [comment]
I was able to run detection on the validation set using `val.py`. So I have those in txt files. 
Beyond that no, I wasn't able to get `detect.py` working with `--save-txt` and `--save-conf`

**Comment by archg2021** [comment]
I am working with just one class, so the below workaround worked for me for saving labels with _detect.py_
https://github.com/hukaixuan19970627/yolov5_obb/blob/6f9ea7d78851d2638cc0d53112cf0b825778e1b3/detect.py#L159-L162

                       # poly = poly.tolist()
                       # line = (cls, *poly, conf) if save_conf else (cls, *poly)  # label format
                        poly_value = [x.item() for x in poly]
                        line = (cls, *poly, conf) if save_conf else (*poly,)  # label format

                        with open(txt_path + '.txt', 'a') as f:
                            f.write(('%g ' * len(line)).rstrip() % line +  ' screws 0'+ '\n')

Where _screws_ is the object class and _difficulty_ is always _0_

**Comment by FireCuda** [comment]
maybe you can try "poly = torch.tensor(poly).view(1, 8).view(-1).tolist()" instead "poly = poly.tolist()"
