### ISSUE TITLE
detect.py error :   RuntimeError: CUDA error: out of memory & CUDA_LAUNCH_BLOCKING=1

### ISSUE THREAD

**Issue by tinly00** [hukaixuan19970627/yolov5_obb#385]
想请问一下作者和各位大佬们：
1. 我跑train已经没问题了
![results](https://user-images.githubusercontent.com/93133444/175753292-46312047-4df1-4d6e-a032-36cfa75f9450.png)

2. 跑detect的时候，报错：
```
detect: weights=runs/train/exp27nice/weights/best.pt, source=/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/newdata/test/, imgsz=[1024, 1024], conf_thres=0.3, iou_thres=0.4, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 2022-5-7 torch 1.10.1+cu102 CUDA:0 (GeForce RTX 2060, 5931MiB)

Traceback (most recent call last):
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 265, in <module>
    main(opt)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 255, in main
    run(**vars(opt))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 84, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/models/common.py", line 309, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 827, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 606, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Process finished with exit code 1

```
![54](https://user-images.githubusercontent.com/93133444/175753330-e5acb321-0ada-4428-adcb-b59c6a58ded3.png)

然后我在开始加了语句之后：
添加的语句：
```
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
```
报错如下：
```
detect: weights=runs/train/exp27nice/weights/best.pt, source=/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/dataset/newdata/test/, imgsz=[1024, 1024], conf_thres=0.3, iou_thres=0.4, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, half=False, dnn=False
YOLOv5 🚀 2022-5-7 torch 1.10.1+cu102 CUDA:0 (GeForce RTX 2060, 5931MiB)

Traceback (most recent call last):
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 265, in <module>
    main(opt)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 255, in main
    run(**vars(opt))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/detect.py", line 84, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/models/common.py", line 309, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "/media/scau/21B1CA0D9A1CBC09/DL/yolov5_obb-master/yolov5_obb-master/models/experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 827, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/scau/anaconda3/envs/yolov5/lib/python3.7/site-packages/torch/cuda/__init__.py", line 606, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: out of memory

Process finished with exit code 1

```
我在detect.py中也貌似找不到有什么参数可以导致out of memory的地方，查了一下，一般都说是cuda异步同步的问题，也有说是class_num的问题。我的是单类目标检测，训练的时候设置的一个单类目标和一个空类，detect的时候没有改，不知道时候和单类识别有关。请问一下作者大大这是什么原因，如何修改代码？
谢谢！
@hukaixuan19970627

**Comment by d5423197** [comment]
你用CPU可以跑吗? 你上面截图里面的device这个参数为什么是空的

**Comment by tinly00** [comment]
我配置单gpu，调训练之前，我没有将device改空，跑不了，改空之后是可以跑detect，但是当时可能训练效果不好检测不出来。后来调好训练再跑detect，不知道为什么跑完训练再跑时候就报这个错了。



---- 回复的原邮件 ----
| 发件人 | Zhonghan ***@***.***> |
| 日期 | 2022年06月27日 14:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] detect.py error : RuntimeError: CUDA error: out of memory & CUDA_LAUNCH_BLOCKING=1 (Issue #385) |

你用CPU可以跑吗? 你上面截图里面的device这个参数为什么是空的

**Comment by hukaixuan19970627** [comment]
其实这个问题你可以用搜索引擎解决，报错提示你当前device的显存不够用

**Comment by tinly00** [comment]
我就是找了挺多帖子，貌似都行不太通。有些说是类class_nun问题，有些说在开头加上CUDA_LAUNCH_BLICKING=1，我加了这个之后，由一堆报错变成只剩下out of memory显存问题，我还在找，还没找到解决的办法。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 15:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] detect.py error : RuntimeError: CUDA error: out of memory & CUDA_LAUNCH_BLOCKING=1 (Issue #385) |

其实这个问题你可以用搜索引擎解决，报错提示你当前device的显存不够用

**Comment by tinly00** [comment]
我晚点要试试device再改改看看行不行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 15:24 |
| 收件人 | ***@***.***> |
| 抄送至 | |
| 主题 | 回复：[hukaixuan19970627/yolov5_obb] detect.py error : RuntimeError: CUDA error: out of memory & CUDA_LAUNCH_BLOCKING=1 (Issue #385) |
我就是找了挺多帖子，貌似都行不太通。有些说是类class_nun问题，有些说在开头加上CUDA_LAUNCH_BLICKING=1，我加了这个之后，由一堆报错变成只剩下out of memory显存问题，我还在找，还没找到解决的办法。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月27日 15:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hukaixuan19970627/yolov5_obb] detect.py error : RuntimeError: CUDA error: out of memory & CUDA_LAUNCH_BLOCKING=1 (Issue #385) |

其实这个问题你可以用搜索引擎解决，报错提示你当前device的显存不够用

**Comment by hukaixuan19970627** [comment]
命令行输入nvidia-smi查看哪些进程在占用gpu，删光这些进程显存不就有了吗
