### ISSUE TITLE
ImportError: nms_rotated_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by Xiaosonghaha** [hukaixuan19970627/yolov5_obb#402]
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    import val  # for end-of-epoch mAP
  File "/home/dingsheng/songchengkun/yolov5_obb/val.py", line 28, in <module>
    from models.common import DetectMultiBackend
  File "/home/dingsheng/songchengkun/yolov5_obb/models/common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/home/dingsheng/songchengkun/yolov5_obb/utils/datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/home/dingsheng/songchengkun/yolov5_obb/utils/augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "/home/dingsheng/songchengkun/yolov5_obb/utils/general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "/home/dingsheng/songchengkun/yolov5_obb/utils/nms_rotated/__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "/home/dingsheng/songchengkun/yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: /home/dingsheng/songchengkun/yolov5_obb/utils/nms_rotated/nms_rotated_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

**Comment by Xiaosonghaha** [comment]
在自己电脑上可以运行，放到服务器上一直报这个错误

**Comment by monument-and-sea-all-the-gift** [comment]
> 在自己电脑上可以运行，放到服务器上一直报这个错误

你nms没有编译和安装吧

**Comment by hukaixuan19970627** [comment]
.so文件在不同的环境依赖中是不一样的，所以换新环境的时候必须重新编译一次，copy过来没用的

**Comment by monument-and-sea-all-the-gift** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月17日(星期天) 晚上6:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hukaixuan19970627/yolov5_obb] 运行时出错 (Issue #402)





 
.so文件在不同的环境依赖中是不一样的，所以换新环境的时候必须重新编译一次，copy过来没用的

**Comment by tinly00** [comment]
我遇到类似问题了，换机载电脑跑也出现类似错误。确实是换环境了，请问如何下载和编译对应版本的nms？

**Comment by matteopantano** [comment]
I have solved by rebuilding, but pip must be prompted at not using the cache. Therefore the command I suggest to use is:
`pip install -v . --no-cache-dir`, moreover, make sure that you deleted any previously generated files in the nms dir like, build etc..
