### ISSUE TITLE
[Torch1.11 error]  src/poly_nms_cuda.cu:4:10: fatal error: THC/THC.h: No such file or directory

### ISSUE THREAD

**Issue by tinly00** [hukaixuan19970627/yolov5_obb#408]
之前的环境是ubuntu18.04，python3.7，cuda10.2
现在上机载电脑，换了环境，ubuntu20.04，python3.8，cuda11.4，torch1.11，运行detect.py出现导包报错：

```
nvidia@ubuntu:~/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master$ python3 detect.py
Traceback (most recent call last):
  File "detect.py", line 32, in <module>
    from models.common import DetectMultiBackend
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/models/common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/nms_rotated/__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/nms_rotated/nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (/home/nvidia/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/nms_rotated/__init__.py)
nvidia@ubuntu:~/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master$ 
```

参考其它帖子，发现可能要重新编译nms，于是在utils/nms_rotated中重新编译：
```
python3 setup.py build_ext --inplace
```

但还是报错：
```
nvidia@ubuntu:~/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/nms_rotated$ python3 setup.py build_ext --inplace
running build_ext
/home/nvidia/.local/lib/python3.8/site-packages/torch/utils/cpp_extension.py:387: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
building '.nms_rotated_ext' extension
creating build/temp.linux-aarch64-cpython-38
creating build/temp.linux-aarch64-cpython-38/src
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DWITH_CUDA -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/TH -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/usr/include/python3.8 -c src/nms_rotated_cpu.cpp -o build/temp.linux-aarch64-cpython-38/src/nms_rotated_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
/usr/local/cuda-11.4/bin/nvcc -DWITH_CUDA -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/TH -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/usr/include/python3.8 -c src/nms_rotated_cuda.cu -o build/temp.linux-aarch64-cpython-38/src/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=compute_72 -gencode=arch=compute_72,code=sm_72 -std=c++14
aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DWITH_CUDA -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/TH -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/usr/include/python3.8 -c src/nms_rotated_ext.cpp -o build/temp.linux-aarch64-cpython-38/src/nms_rotated_ext.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
/usr/local/cuda-11.4/bin/nvcc -DWITH_CUDA -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/TH -I/home/nvidia/.local/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.4/include -I/usr/include/python3.8 -c src/poly_nms_cuda.cu -o build/temp.linux-aarch64-cpython-38/src/poly_nms_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1013\" -DTORCH_EXTENSION_NAME=nms_rotated_ext -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_72,code=compute_72 -gencode=arch=compute_72,code=sm_72 -std=c++14
src/poly_nms_cuda.cu:4:10: fatal error: THC/THC.h: No such file or directory
    4 | #include <THC/THC.h>
      |          ^~~~~~~~~~~
compilation terminated.
error: command '/usr/local/cuda-11.4/bin/nvcc' failed with exit code 1
nvidia@ubuntu:~/ros_workspace/src/yolov5_ros/src/yolov5_obb-master/yolov5_obb-master/utils/nms_rotated$ 
```

请问有什么办法解决？谢谢！@hukaixuan19970627@monument-and-sea-all-the-gift

**Comment by tinly00** [comment]
之前的环境可以跑通

**Comment by LUO77123** [comment]
好像说的torch1.11不支持，你试一下torch1.12,(注释掉了“#include <THC /THC.h>”，并添加“#include <c10/cuda/CUDACachingAllocator.h>”)   或者降低版本到1.10，应该就可以

**Comment by matteopantano** [comment]
Indeed I solved this issue by downgrading to 1.10 and everything worked out smoothly!

**Comment by tinly00** [comment]
> 

因为我是在机载电脑AGX上装的，这是ARM架构，我按照官方的安装包，刷机的时候默认装了CUDA11.4，然后我看了官方提供对应的torch是1.11，不知道1.12是否可以，请问你的CUDA版本是多少呢？

**Comment by tinly00** [comment]
> Indeed I solved this issue by downgrading to 1.10 and everything worked out smoothly!

BUT my cuda is 11.4， it seems need torch1.11

![image](https://user-images.githubusercontent.com/93133444/180215512-80fd926e-ef57-4522-ad70-a2678d382ef3.png)

**Comment by tinly00** [comment]
> Indeed I solved this issue by downgrading to 1.10 and everything worked out smoothly!

is your CUDA 11.4 and it worked with torch 1.11?
thank u!

**Comment by matteopantano** [comment]
Well, with CUDA 11.4 it will not work @tinly00. One rule of thumb when developing with AI, never use the latest version! One really useful table for me to select which pytorch to use is [this](https://pytorch.org/get-started/previous-versions/). I recommend you to choose out of this the version that best suit your needs... and you should do some trial and errors until you find the best solution, as of now CUDA 10.2 seems the most usable framework which works with several AI software, I am personally using just this one!

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb/issues/151
torch1.11可以参考这个issue，里面提的PR是一种解决方案，更高版本的torch就不支持可不可以了
