### ISSUE TITLE
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import)

### ISSUE THREAD

**Issue by Syazaniwhd** [hukaixuan19970627/yolov5_obb#443]
**Run:** 
python train.py --data C:\Users\PC\Documents\UROPS\YOLOV5_OBB\datasets\roboflow\data.yaml --epochs 10 --batch-size 1 --img 1024 --device 0 --exist-ok

**Error:**

 (yolov5obb) C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb>python train.py --data C:\Users\PC\Documents\UROPS\YOLOV5_OBB\datasets\roboflow\data.yaml --epochs 10 --batch-size 1 --img 1024 --device 0 --exist-ok
Traceback (most recent call last):
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\train.py", line 34, in <module>
    import val  # for end-of-epoch mAP
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\val.py", line 28, in <module>
    from models.common import DetectMultiBackend
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\models\common.py", line 23, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\augmentations.py", line 12, in <module>
    from utils.general import LOGGER, check_version, colorstr, resample_segments, segment2box
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\general.py", line 35, in <module>
    from utils.nms_rotated import obb_nms
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\nms_rotated\__init__.py", line 1, in <module>
    from .nms_rotated_wrapper import obb_nms, poly_nms
  File "C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\nms_rotated\nms_rotated_wrapper.py", line 4, in <module>
    from . import nms_rotated_ext
ImportError: cannot import name 'nms_rotated_ext' from partially initialized module 'utils.nms_rotated' (most likely due to a circular import) (C:\Users\PC\Documents\UROPS\YOLOV5_OBB\yolov5_obb\utils\nms_rotated\__init__.py)

May I know how do i resolve this circular import issue?

**Comment by tcotte** [comment]
You did not install well the package. Follow instructions on install.md

**Comment by prashant-dn** [comment]
The installation doesn't complete if pytorch is 2+. It throws `THC not found`, discussed [here](https://discuss.pytorch.org/t/question-about-thc-thc-h/147145/5). 

The workaround is to try and install it using the older versions of pytorch 1.6. Where this issue shouldn't pop up. For me even this wasn;t possible, so I just comment out the requirement of `nms_rotated`

* Install nms_rotated inside `yolov5_obb/utils/nms_rotated#` using official yolov5-obb [instructions](https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/install.md). 

* Comment out `from . import nms_rotated_ext` from `CheckoutAccuracy/utilities/yolov5_utils/utils/nms_rotated/nms_rotated_wrapper.py`

Now just go on with the training.

**Comment by yasmine-lkl** [comment]
I'm encountering the same issue and don't know how to resolve it. I suspect there might be an incompatibility between CUDA and PyTorch
