### ISSUE TITLE
Dimensionality issue when calculating OBB-NMS

### ISSUE THREAD

**Issue by Suppersine** [hukaixuan19970627/yolov5_obb#524]
I was working on my own adaptation, which is here:
https://github.com/Suppersine/yolov7_obb_expm

and here is my notebook:
https://colab.research.google.com/drive/1-cwr8-k7xKYyaD5pTN24RZv3rpPaWfvi?usp=sharing

With the training stage stuck at utils/general.py line 828:

```
mage sizes 640 train, 640 test
Using 0 dataloader workers
Logging results to runs/train/exp
Starting training for 10 epochs...

     Epoch   gpu_mem       box       obj       cls     total    labels  img_size
       0/9     2.57G         0   0.01427         0   0.01427         0       640: 100% 157/157 [00:29<00:00,  5.25it/s]
               Class      Images      Labels           P           R      mAP@.5  mAP@.5:.95:   0% 0/2 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 674, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 453, in train
    results, maps, times = test.test(opt.data,
  File "/content/yolov7_obb_expm/test.py", line 167, in test
    out =  non_max_suppression_obb(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls)
  File "/content/yolov7_obb_expm/utils/general.py", line 828, in non_max_suppression_obb
    conf, j = x[:, 5:class_index].max(1, keepdim=True)
IndexError: max(): Expected reduction dim 1 to have non-zero size.
```

I still have no idea tow to overcome, do you have any?

**Comment by blackHorz** [comment]
Did you have solved it?

**Comment by Suppersine** [comment]
yep, I did

**Comment by N-enthusiasm** [comment]
How did you solve it?
