### ISSUE TITLE
Typcasting float to long Runtime Error

### ISSUE THREAD

**Issue by gibotsgithub** [hukaixuan19970627/yolov5_obb#539]
Epoch   gpu_mem       box       obj       cls     theta    labels  img_size
  0%|          | 0/4 [00:00<?, ?it/s]                                                                                                                                                                              
Traceback (most recent call last):
  File "/home/server/scanning/python-server/ocri-python/app/test/harshal_yolo/yolov5_obb/train.py", line 633, in <module>
    main(opt)
  File "/home/server/scanning/python-server/ocri-python/app/test/harshal_yolo/yolov5_obb/train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/server/scanning/python-server/ocri-python/app/test/harshal_yolo/yolov5_obb/train.py", line 326, in train
    loss, loss_items = compute_loss(pred, targets.to(device))  # loss scaled by batch_size
  File "/home/server/scanning/python-server/ocri-python/app/test/harshal_yolo/yolov5_obb/utils/loss.py", line 135, in __call__
    tcls, tbox, indices, anchors, tgaussian_theta = self.build_targets(p, targets)  # targets
  File "/home/server/scanning/python-server/ocri-python/app/test/harshal_yolo/yolov5_obb/utils/loss.py", line 265, in build_targets
    indices.append((b, a, gj.clamp_(0, feature_wh[1] - 1), gi.clamp_(0, feature_wh[0] - 1)))  # image, anchor, grid indices
RuntimeError: result type Float can't be cast to the desired output type long int

How do I fix this? It worked in colab, but not running on my laptop

**Comment by ZHOU-ZHOU-YI** [comment]
我遇到了相同的问题，解决方案看这个链接：https://blog.csdn.net/Thebest_jack/article/details/125649451

**Comment by Stark-Bear** [comment]
Needs to replace two lines in the file loss.py .
1、Replace “anchors = self.anchors[i] ”  with "anchors, shape = self.anchors[i], p[i].shape"
2、Replace “indices.append((b, a, gj.clamp_(0, feature_wh[1] - 1), gi.clamp_(0, feature_wh[0] - 1)))”  with "indices.append((b, a, gj.clamp_(0, shape[2] - 1), gi.clamp_(0, shape[3] - 1)))" .

In addition , after this has fixed , if anyone has the "AttributeError: 'FreeTypeFont' object has no attribute 'getsize' " ,  just  tpye  pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple  Pillow==9.5 .  Pillow >=10  has delete the attribute "getsize()"
