### ISSUE TITLE
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

### ISSUE THREAD

**Issue by NefarianZ** [hukaixuan19970627/yolov5_obb#547]
Hey Hu, thanks for your great work . After I start run my own dataset training 【python train.py --weights 'yolov5s.pt' --cfg models/yolov5s.yaml --data data/customer.yaml --hyp data/hyps/obb/hyp.finetune_dota.yaml --epochs 350 --batch-size 8 --imgsz 768 --workers 0】, it show below error. Can you please tell me how to fix it ? Thanks again.

Model Summary: 270 layers, 7507786 parameters, 7507786 gradients, 17.5 GFLOPs

Scaled weight_decay = 0.0005
optimizer: Adam with parameter groups 57 weight, 60 weight (no decay), 60 bias
train: Scanning 'dataset\customer\train.cache' images and labels... 270 found, 0 missing, 0 empty, 0 corrupted: 100%|█|train: Scanning 'dataset\customer\train.cache' images and labels... 270 found, 0 missing, 0 empty, 0 corrupted: 100%|█|
val: Scanning 'dataset\customer\valid.cache' images and labels... 90 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 90val: Scanning 'dataset\customer\valid.cache' images and labels... 90 found, 0 missing, 0 empty, 0 corrupted: 100%|█| 90
module 'signal' has no attribute 'SIGALRM'

AutoAnchor: 4.65 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset
Image sizes 768 train, 768 val
Using 0 dataloader workers
Logging results to runs\train\exp6
Starting training for 350 epochs...

 Epoch   gpu_mem       box       obj       cls    labels  img_size
0%| | 0/34 [00:01<?, ?it/s]
Traceback (most recent call last):
File "train.py", line 631, in
main(opt)
File "train.py", line 528, in main
train(opt.hyp, opt, device, callbacks)
File "train.py", line 344, in train
mloss = (mloss * i + loss_items) / (i + 1) # update mean losses
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

(base) E:\AI\yolov5_obb-master>

**Comment by yuweiApp** [comment]
I also encountered this problem before, and the reason was that the K-means clustering algorithm required too little data. You should increase the size of the dataset. This is the reason why.
