### ISSUE TITLE
install yolov5_obb error

### ISSUE THREAD

**Issue by ramdhan1989** [hukaixuan19970627/yolov5_obb#556]
Hi, anyone can share how to install this repo correctly. I got a problem when running setup.py as follow :
```
running develop
C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
creating nms_rotated.egg-info
writing nms_rotated.egg-info\PKG-INFO
writing dependency_links to nms_rotated.egg-info\dependency_links.txt
writing top-level names to nms_rotated.egg-info\top_level.txt
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
reading manifest file 'nms_rotated.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
running build_ext
error: [WinError 2] The system cannot find the file specified
```
I used windows with following cuda information.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.65       Driver Version: 511.65       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:24:09_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```
please advise
thanks

**Comment by ramdhan1989** [comment]
update my error is like this:
```
(obb) D:\xx\obb\yolov5_obb-master\utils\nms_rotated>python setup.py develop
running develop
C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
creating nms_rotated.egg-info
writing nms_rotated.egg-info\PKG-INFO
writing dependency_links to nms_rotated.egg-info\dependency_links.txt
writing top-level names to nms_rotated.egg-info\top_level.txt
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
reading manifest file 'nms_rotated.egg-info\SOURCES.txt'
writing manifest file 'nms_rotated.egg-info\SOURCES.txt'
running build_ext
building '.nms_rotated_ext' extension
creating D:\Ramdhan\obb\yolov5_obb-master\utils\nms_rotated\build
creating D:\Ramdhan\obb\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-37
creating D:\Ramdhan\obb\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-37\Release
creating D:\Ramdhan\obb\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-37\Release\src
Emitting ninja build file D:\Ramdhan\obb\yolov5_obb-master\utils\nms_rotated\build\temp.win-amd64-cpython-37\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: build.ninja:3: lexing error

Traceback (most recent call last):
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\torch\utils\cpp_extension.py", line 1672, in _run_ninja_build
    env=env)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    zip_safe=False)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\torch\utils\cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\torch\utils\cpp_extension.py", line 691, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\torch\utils\cpp_extension.py", line 1360, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\Owner\anaconda3\envs\obb\lib\site-packages\torch\utils\cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by peng30025** [comment]
I have the same problem with you ,who has the solution?

**Comment by Schweizliu** [comment]
> I have the same problem with you ,who has the solution?

me too,Do you have a good solution

**Comment by wnzlff** [comment]
I am running into the same problem.

**Comment by Schweizliu** [comment]
> I am running into the same problem.

https://github.com/Egrt/yolov7-obb/issues/24我解决了，你试试这个方法
