### ISSUE TITLE
训练的时候报错：FileNotFoundError: [Errno 2] No such file or directory: 'dataset/train_rate1.0_split1024_gap200/labelTxt.cache'

### ISSUE THREAD

**Issue by NOON47** [hukaixuan19970627/yolov5_obb#562]
借助[https://github.com/hukaixuan19970627/yolov5_obb/blob/master/docs/GetStart.md](url)，可以跑val.py，可以跑detect。但是在用自己数据进行训练的时候报如下的错误：
cache_labels = dataset/train_rate1.0_split1024_gap200/labelTxt.cache,prefix=train: 
Traceback (most recent call last):
  File "/home/test/hdd2t/test/DL/yolov5_obb/utils/datasets.py", line 437, in __init__
    cache, exists = np.load(cache_path, allow_pickle=True).item(), True  # load dict
  File "/home/test/miniconda3/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/train_rate1.0_split1024_gap200/labelTxt.cache'
During handling of the above exception, another exception occurred:
数据的格式是跟demo一样的：
751.0 745.0 454.0 768.0 449.0 703.0 746.0 680.0 a1 0
554.0 388.0 749.0 670.0 698.0 705.0 502.0 424.0 a1 0
 @hukaixuan19970627 即使是使用原始数据，也是报这个错误，请问这个怎么解决？

**Comment by NOON47** [comment]
数据的格式是跟demo一样的：
751.0 745.0 454.0 768.0 449.0 703.0 746.0 680.0 a1 0
554.0 388.0 749.0 670.0 698.0 705.0 502.0 424.0 a1 0

**Comment by CSberlin** [comment]
应该是dataset.py的LoadImagesAndLabels的成员出了问题这里出了问题, 加上这行代码试试
`if isinstance(cls_names, dict):
            self.cls_names = list(cls_names.values())
        else:
            self.cls_names = cls_names`
