### ISSUE TITLE
Faster method for calculating CSL labels

### ISSUE THREAD

**Issue by yoloyash** [hukaixuan19970627/yolov5_obb#568]
Hello big brother @hukaixuan19970627 , I'm currently trying to calculate csl labels using the function given by you gaussian_label_cpu. However, for large tensors of size >=20k the function seems very slow. Could you maybe help me write a faster implementation for it using pytorch and cuda?

**Comment by ooowuyaooo** [comment]
> Hello big brother @hukaixuan19970627 , I'm currently trying to calculate csl labels using the function given by you gaussian_label_cpu. However, for large tensors of size >=20k the function seems very slow. Could you maybe help me write a faster implementation for it using pytorch and cuda?

seems you have to do this function yourself,, maybe faster...

**Comment by LeiaJ520** [comment]
How to set parameters to use CSL labels? I set use_gaussian=True in the poly2rbox function in yolov5_obb/utils/rboxs_utils.py, but there is an error in training. The error content is as follows:
tuple indices must be integers or slices, not tuple
Traceback (most recent call last):
  File "/home/lxj/yolov5_obb/train.py", line 633, in <module>
    main(opt)
  File "/home/lxj/yolov5_obb/train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/lxj/yolov5_obb/train.py", line 238, in train
    check_anchors(dataset, model=model, thr=hyp['anchor_t'], imgsz=imgsz)
  File "/home/lxj/yolov5_obb/utils/autoanchor.py", line 49, in check_anchors
    ls_edges.append(rboxes[:, 2:4])
TypeError: tuple indices must be integers or slices, not tuple
