### ISSUE TITLE
遇到了RuntimeError: Not compiled with GPU support 

### ISSUE THREAD

**Issue by qqdalao** [hukaixuan19970627/yolov5_obb#582]
Traceback (most recent call last):
File "E:/WYH/yolov5_obb-master/train.py", line 635, in
main(opt)
File "E:/WYH/yolov5_obb-master/train.py", line 530, in main
train(opt.hyp, opt, device, callbacks)
File "E:/WYH/yolov5_obb-master/train.py", line 373, in train
compute_loss=compute_loss)
File "D:\Anaconda\envs\dx\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, *kwargs)
File "E:\WYH\yolov5_obb-master\val.py", line 206, in run
out = non_max_suppression_obb(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls) # list(n, [xylsθ, conf, cls]) θ ∈ [-pi/2, pi/2)
File "E:\WYH\yolov5_obb-master\utils\general.py", line 853, in non_max_suppression_obb
_, i = obb_nms(rboxes, scores, iou_thres)
File "E:\WYH\yolov5_obb-master\utils\nms_rotated\nms_rotated_wrapper.py", line 41, in obb_nms
inds = nms_rotated_ext.nms_rotated(dets_th, scores, iou_thr)
RuntimeError: Not compiled with GPU support 
大佬，出现了这个问题，然后我看nms_rotated_wrappe中显示没有nms_rotated_ext，并且我在utils\nms_rotated中有nms_rotated_ext.cp37-win_amd64

**Comment by qqdalao** [comment]
大佬们，还遇到一个问题，就是训练完以后得到的train_batchx图片里的图都是歪的是为什么

**Comment by qqdalao** [comment]
![train_batch0](https://github.com/hukaixuan19970627/yolov5_obb/assets/138202243/015b2f4f-50fe-4a9b-b0fd-4fb92db61ec3)

**Comment by Freeman-Cai** [comment]
你把augment改一下图就不会旋转了

**Comment by chinhnt0110** [comment]
> 

I ran on google colab and faced the same problem. I reinstalled `pytorch` by conda and it worked.
`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge`
