### ISSUE TITLE
验证时候的错误

### ISSUE THREAD

**Issue by wristlong** [hukaixuan19970627/yolov5_obb#600]
classname: vehicle
This class is not be detected in your dataset: vehicle
Traceback (most recent call last):
  File "DOTA_devkit/dota_evaluation_task1.py", line 345, in <module>
    main()
  File "DOTA_devkit/dota_evaluation_task1.py", line 340, in main
    map = map/(len(classnames)-skippedClassCount)
ZeroDivisionError: division by zero

不知道怎么解决

**Comment by wangchuangg** [comment]
我也出现了这种问题，不知道怎么去解决

**Comment by wangchuangg** [comment]
在执行获得Get the OBB metrics时，出现了
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/15517fbd-f487-4050-8174-f0a0132498d7)

**Comment by wangchuangg** [comment]
在使用dota_evaluation_task1.py获得obb  metrics 需要选择对应的数据集的类别，在该代码里修成与使用数据集类一致的就行。

**Comment by wangchuangg** [comment]
> classname: vehicle This class is not be detected in your dataset: vehicle Traceback (most recent call last): File "DOTA_devkit/dota_evaluation_task1.py", line 345, in main() File "DOTA_devkit/dota_evaluation_task1.py", line 340, in main map = map/(len(classnames)-skippedClassCount) ZeroDivisionError: division by zero
> 
> 不知道怎么解决

在使用dota_evaluation_task1.py获得obb metrics 需要选择对应的数据集的类别，在该代码里修成与使用数据集类一致的就行。
![image](https://github.com/hukaixuan19970627/yolov5_obb/assets/141005166/40a04878-6720-4c16-9c75-a5f8918f77e0)
