### ISSUE TITLE
无法读取标签进行训练

### ISSUE THREAD

**Issue by Magiczxt** [hukaixuan19970627/yolov5_obb#605]
我在使用SARSSDD数据集训练Yolov5_obb模型，但训练时对于训练集的每一张图像，都会报出如下的警告信息：
train: WARNING: E:\yolov5_obb-master\data\SARSSDD\JPEGImages\001154.jpg: ignoring corrupt image/label: 'list' object has no attribute 'values'
然后最终无法训练，从报错的信息来看应该是标签没有正确读入：
Traceback (most recent call last):
  File "E:\yolov5_obb-master\train.py", line 633, in <module>
    main(opt)
  File "E:\yolov5_obb-master\train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "E:\yolov5_obb-master\train.py", line 213, in train
    train_loader, dataset = create_dataloader(train_path, imgsz, batch_size // WORLD_SIZE, gs, names, single_cls,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\yolov5_obb-master\utils\datasets.py", line 101, in create_dataloader
    dataset = LoadImagesAndLabels(path, names, imgsz, batch_size,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\yolov5_obb-master\utils\datasets.py", line 444, in __init__
    labels, shapes, self.segments = zip(*cache.values())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
然后我标签的格式是按照DOTA的格式写的（四点坐标，类别和difficult，一共十个数），按理说应该不存在格式不匹配的问题啊，谁能告诉我怎么回事

**Comment by MuhammadRamzan4** [comment]
@Magiczxt 
Do you find any solution? Facing same issue

**Comment by falibabaei** [comment]
@Magiczxt @MuhammadRamzan4 
Any solution yet?

**Comment by Loading-xxx** [comment]
@Magiczxt  请问你解决了吗，我之前跑demo没有问题，后来在DOTAV1.5 train里随便找了几张图换进去就报这种错，再后来换回demo也报错了...

**Comment by lppiu** [comment]
相同问题，已经解决：numpy版本过高
换两个包：pip install unmpy==1.22.2
pip install pandas==1.2.0

**Comment by ConvAndConv** [comment]
> 相同问题，已经解决：numpy版本过高 换两个包：pip install unmpy==1.22.2 pip install pandas==1.2.0

换了，依然没有解决啊

**Comment by leileilei2000** [comment]
> 相同问题，已经解决：numpy版本过高 换两个包：pip install unmpy==1.22.2 pip install pandas==1.2.0

wcwcwc！！！真可以了
