### ISSUE TITLE
训练完第一个epoch报错

### ISSUE THREAD

**Issue by Chenjiangwen** [hukaixuan19970627/yolov5_obb#608]
Traceback (most recent call last):
  File "D:\mydata\Py_project\UAV\yolov5_obb\train.py", line 633, in <module>
    main(opt)
  File "D:\mydata\Py_project\UAV\yolov5_obb\train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "D:\mydata\Py_project\UAV\yolov5_obb\train.py", line 364, in train
    results, maps, _ = val.run(data_dict,
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator.DESKTOP-SA93FAA\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\mydata\Py_project\UAV\yolov5_obb\val.py", line 206, in run
    out = non_max_suppression_obb(out, conf_thres, iou_thres, labels=lb, multi_label=True, agnostic=single_cls) # list*(n, [xylsθ, conf, cls]) θ ∈ [-pi/2, pi/2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mydata\Py_project\UAV\yolov5_obb\utils\general.py", line 853, in non_max_suppression_obb      
    _, i = obb_nms(rboxes, scores, iou_thres,)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\mydata\Py_project\UAV\yolov5_obb\utils\nms_rotated\nms_rotated_wrapper.py", line 37, in obb_nms
    ori_inds = ori_inds[~too_small]
               ~~~~~~~~^^^^^^^^^^^^
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by davidsvy** [comment]
This can be fixed by changing line 36 in ```yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py``` from:
```ori_inds = torch.arange(dets_th.size(0))```
to
```ori_inds = torch.arange(dets_th.size(0), device=dets_th.device)```

**Comment by Chenjiangwen** [comment]
> This can be fixed by changing line 36 in `yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py` from: `ori_inds = torch.arange(dets_th.size(0))` to `ori_inds = torch.arange(dets_th.size(0), device=dets_th.device)`

Thank you, I have successfully resolved this issue based on your description. However, I encountered the same problem #437  again after completing the first epoch of training 。According to his approach, I would like to know if such modifications would affect the outcome.

**Comment by vincentliang** [comment]
that is helpfull!

**Comment by Stark-Bear** [comment]
> This can be fixed by changing line 36 in `yolov5_obb/utils/nms_rotated/nms_rotated_wrapper.py` from: `ori_inds = torch.arange(dets_th.size(0))` to `ori_inds = torch.arange(dets_th.size(0), device=dets_th.device)`

A helpful solution .
