### ISSUE TITLE
换了OTALoss，训练报了错（i changed to use OTALoss, and when starting training, the errors occur）

### ISSUE THREAD

**Issue by oldg00se** [hukaixuan19970627/yolov5_obb#648]
Traceback (most recent call last):
  File "e:\yolov5-6.1-ota\train-ota.py", line 655, in <module>
    main(opt)
  File "e:\yolov5-6.1-ota\train-ota.py", line 551, in main
    train(opt.hyp, opt, device, callbacks)
  File "e:\yolov5-6.1-ota\train-ota.py", line 342, in train
    loss, loss_items = compute_loss(pred, targets.to(device), imgs)  # loss scaled by batch_size
  File "E:\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "e:\yolov5-6.1-ota\utils\ota.py", line 147, in forward
    return self.get_losses(
  File "e:\yolov5-6.1-ota\utils\ota.py", line 337, in get_losses
    reg_target = gt_bboxes_per_image[matched_gt_inds]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by ChristoCai** [comment]
same problem, do you solve?
